---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: to install web srver(apt-get install apache2)
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: i want to start web server in debian(service apache2 start)
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"


    
    - name: i want to start web server in redhat(service httpd start)
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"